import tweepy

API_KEY = "INPUT_HERE"
API_SECRET = "INPUT_HERE"
BEARER_TOKEN = "INPUT_HERE"
ACCESS_TOKEN = "INPUT_HERE"
ACCESS_TOKEN_SECRET = "INPUT_HERE"

client = tweepy.Client(BEARER_TOKEN, API_KEY, API_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
auth = tweepy.OAuth1UserHandler(API_KEY, API_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)
